version: '3.8' # optional since v1.27.0
name: nurse-backend
services:
    db:
        container_name: nurse_db
        image: postgres:15.3-alpine
        restart: always
        ports:
            - ${DATABASE_PORT}:5432
        volumes:
            - nurse_vol:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        networks:
            - nurse_net
volumes:
    nurse_vol:
        external: false
networks:
    nurse_net:
        driver: bridge
        external: false
