version: '3.8'
services:
    postgres:
        container_name: postgres
        image: postgres:15.3-alpine
        ports:
            - '${DATABASE_PORT}:5432'
        volumes:
            - nurse_vol:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        networks:
            - nurse_net
        restart: always
volumes:
    nurse_vol:
        external: false

networks:
    nurse_net:
        driver: bridge
        external: false
